name: One-time Scheduled Publish

on:
  schedule:
    - cron: "20 9 1 9 *" # UTC 09:20 → 北京时间 17:20，2025-09-01
  workflow_dispatch: # 保留手动触发测试

jobs:
  publish-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Add publish label
        uses: peter-evans/add-labels@v2
        with:
          labels: publish
          issue-number: 13  # 替换成你的 Issue 编号

      - name: Remove draft label
        uses: peter-evans/remove-labels@v2
        with:
          labels: draft
          issue-number: 13
